silq/analysis/fit_toolbox.py

This causes issues where initial parameters are sometimes calculated twice. It can also raise an error

Fix: do not determine fit parameters if already performed

---

silq/instrument_interfaces/interface.py

Removes the following items from interface snapshots:
- instrument (instruments should be added to the station separately)
- pulse_sequence
- input_pulse_sequence
- targeted_pulse_sequence
- targeted_input_pulse_sequence
Requires https://github.com/nulinspiratie/Qcodes/pull/74

Clean interface snapshot

---

silq/instrument_interfaces/keysight/E8267D_interface.py

In IQ modulation mode if you pulse only with single frequency, i.e. you don't need IQ modulation, it shows an error. It is fixed now - was copied by Serwan from Queenie.

fixed IQ modulation mode for single frequency pulses

---

silq/__init__.py

Small fix for unix-like paths.
I'm still unsure about [one line ](https://github.com/nulinspiratie/SilQ/blob/f70ec5687c08266e47a354f45b311117a86c6716/silq/__init__.py#L463), I can't figure out why pulse sequences have a '\\\\' in them by default. I can't find where this gets added, but it doesn't seem to be an issue for now so long as pulse sequences aren't created on a unix-like system, I suppose.

Make the path OS independent for get_pulse_sequence.

---

silq/pulses/pulse_types.py

This enables backwards-compatibility with old pulse sequences.

Add a check if phase_reference is an attr of the class.

---

silq/instrument_interfaces/keysight/Keysight_SD_DIG_interface.py

This was causing a bug with snapshotting.
Tested and good to go

Remove acquisition controller from Keysight SD snapshot

---

silq/__init__.py

Originally the only check was if `ipykernel` was in `sys.modules`.
While this usually works in detecting if we're using ipython, it fails when a new process is started using multiprocessing. In this situation `ipykernel` exists, but the process is not using ipython.
This modification was needed for https://github.com/nulinspiratie/Qcodes/pull/79

Fix: Check if using ipython before registering magic

---

silq/__init__.py

This PR removes the clearing of temporary acquisition parameter settings for the new Measurement.
So the following won't work anymore in the new Measurement:
```Python
NMR_parameter.temporary_settings(samples=200)
```
The reason is that keeping the ability to implement this is rather annoying to program, and its functionality is superseded by `Measurement.mask`

fix:Remove clear temporary settings at end of measurement

---

silq/parameters/acquisition_parameters.py

In the new NMR pulse sequence, there is an additional "read" post-pulse after NMR pulse that can be used for electron-readout in EDSR measurements. This parameter was not tested yet and requires update to the new pulse sequence first to work

added new EDSR parameter based on NMR parameter

---

silq/parameters/acquisition_parameters.py

I'm trying to make sure that every acquisition parameter has the option to specify which acquisition channel it will analyse for information.
This became apparent when measuring 2 devices simultaneously, where the DCParameter could only analyse the channel 'output'.

Feature: add option to specify  acquisition channel label in acquisition parameters

---

silq/instrument_interfaces/AlazarTech/ATS_interface.py

I noticed that segmenting traces in the ATS (when `pulse.average_mode == 'segment:{N}') was slow, especially when using the DCSweepPlot.
Here we speed this process up quite a bit

Speed up segmenting of traces in ATS

---

silq/tools/circuit_tools.py

In RB sequences for Randomized Benchmarking there is an additional Q character that is needed to properly use pygsti analysis of the results later. But to measure first, we need to get rid of it.

added deletion of Q character for RB sequences

---

silq/instrument_interfaces/keysight/fpga_interfaces/PCDDS_interface.py

Temporarily revert the PCDDS phase reference such that it is always phase coherent, because now it's the wrong way around. 
At least until we figure out #248

PCDDS revert absolute / relative phase

---

silq/instrument_interfaces/keysight/E8267D_interface.py

Adds the parameter `microwave_interface.envelope_IQ` to the Keyisght E8267D microwave interface.
By default (`envelop_IQ=True`), the envelope padding is applied to the IQ inputs, while the marker pulses are the length of the actual pulse.
When `envelope_IQ = False`, the envelope padding is instead applied to the marker pulses, and the IQ inputs are only nonzero for the duration of the pulses.
This feature is useful if you want multiple pulses that are more closely spaced than the envelope padding.
Note that to avoid pulse overlaps, any overlapping marker pulses are merged into a single longer marker pulse.
@RostyslavSavytskyy I think we should merge this PR before #233 since it is a fairly small PR and could otherwise lead to conflicts

add envelope_IQ to keysight e8267D interface

---

silq/meta_instruments/layout.py
silq/pulses/pulse_types.py

This pulse will be ignored by the layout. Useful if you for instance need a delay between pulses

Add DummyPulse

---

silq/instrument_interfaces/keysight/Keysight_SD_AWG_interface.py

Fixes another minor issue regarding keysight indexing caused by `default_sampling_rates` still having hard-coded zero-based indexing.
Also adds the option for triggering lines that have an inverted connection (e.g. Pulseblaster DDS)

Fix: AWG indexing issues and inverted connection

---

silq/instrument_interfaces/lecroy/ArbStudio1104_interface.py

Fixes #265.
More details pertaining to this issue:
@RostyslavSavytskyy and I did some testing and found that if you stopped the layout and started it again, the arbstudio would continue outputting on an unused channel, however if you stopped the layout, and explicitly started the triggering to the arbstudio (in this case the pulseblaster ESR Pro), then started the arbstudio, the unused channel would no longer output erroneously. 
Very strange! In any case, this seems to fix the issue.

Force arbstudio to load unused channels with a DC pulse

---

silq/parameters/acquisition_parameters.py

This is needed to prevent an error when using this parameter in a measurement context where setpoints are saved.

Add setpoint_labels to DCSweepParameter

---

silq/instrument_interfaces/spincore/PulseBlasterESRPRO_interface.py

In the cases when AWG does not demand a trigger for the first pulse in its sequence (e.g. arbstudio), a pulseblaster needs to wait this additional time between the end (start) of the sequence and the second pulse. Otherwise, the next trigger (for the second pulse) will appear right after the trigger in the end of the sequence, hence cutting out the first pulse, e.g. pre-delay in the plunge pulse is completely gone and is defined only by pulse_sequence.final_delay.

fixes timing issues with triggering

---

.gitignore
silq/parameters/acquisition_parameters.py
silq/pulses/pulse_sequences.py

Created a  parameter for the existing NMRCPMGPulseSequence, which was not yet implemented. This parameter takes care of the differences in the inter delay times between pi/2 and pi pulses in a CPMG sequence. Please note that this NMPRCPMGParameter can be used as a NMRRamseyParameter by setting the number of pi pulses to 0.

Creation of the NMRCPMGParameter

---

silq/meta_instruments/layout.py
silq/tools/trace_tools.py

Fixes #224.
By using the latest version of hdf5 we gain access to some extra features, including single-writer multiple-reader (SWMR) mode.
We may wish to specify the exact version we want to use, going forward, to ensure backwards compatibility is more easily assured.
- Before
- Storing 600,000 points takes ~ 260 +- 58 ms.
- Storing 1500 points takes ~5.7 +- 4.7 ms
- After 
- Storing 600,000 points takes ~ 230 +- 50 ms.
- Storing 1500 points takes ~1 +- 4 ms

Enable single-writer multiple-reader access to trace files.

---

silq/instrument_interfaces/rohde_schwarz/SGS100A_interface.py

This is needed when doing most forms of dynamical decoupling sequences.

Rohde and Schwarz interface: Ensure IQ modulation is enabled if different pulse phases are used

---

silq/analysis/analysis.py

In composite pulse sequences if you want to save also the traces of the applied pulses (plunge) and not just of the "read_initialize", the function (find_high_low) that determines the threshold voltage crushes due to the different sizes of the traces in each pulse. This modification quickly fixes the bug, but then the find_high_low function uses all traces to determine the threshold voltage which is useless. So we either need to determine the threshold voltage only when it is not set manually or be able to extract an use the traces only from read_initialize as it was done in non-composite parameters and pulse sequences.
**UPDATE**
It causes further crashes in the analysis, apparently composite analysis cannot handle the option when we save also traces that do not need to be analyzed.

fixes the issue when saving pulse traces as well
